# Generated by Django 2.1.7 on 2019-03-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Blocked'), (1, 'Active')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('likes', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Blocked'), (1, 'Active')], default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('dish_type', models.IntegerField(choices=[(0, 'Salad'), (1, 'FIRST'), (2, 'SECOND'), (3, 'SOUP'), (4, 'DESSERT'), (5, 'DRINK')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Customuser')),
            ],
        ),
    ]
